name: Push

on:
  workflow_dispatch:
  push:

permissions:
  packages: write
  contents: read
  id-token: write

env:
  GITHUB_USERNAME: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
  CENTRAL_TOKEN: ${{ secrets.CENTRAL_TOKEN }}
  GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
  GPG_PRIVATE_KEY_PASSPHRASE: ${{ secrets.GPG_PRIVATE_KEY_PASSPHRASE }}
  CI: true

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Execute tests
        run: ./gradlew test

  maven_snapshot_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set snapshot version suffix
        run: |
          GIT_HASH=$(git rev-parse --short "$GITHUB_SHA")
          echo "SW_RUM_VERSION_SUFFIX=$GIT_HASH-SNAPSHOT" >> $GITHUB_ENV

      - name: Publish
        run:
          ./gradlew publishToSonatype